In [1]:
import faiss

In [2]:
index = faiss.read_index("bills.index")

In [3]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("nomic-ai/nomic-embed-text-v1.5", trust_remote_code=True)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/255 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/140 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/120 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

configuration_hf_nomic_bert.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/nomic-ai/nomic-bert-2048:
- configuration_hf_nomic_bert.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


modeling_hf_nomic_bert.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/nomic-ai/nomic-bert-2048:
- modeling_hf_nomic_bert.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


model.safetensors:   0%|          | 0.00/547M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/695 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/286 [00:00<?, ?B/s]

In [ ]:
sentences = ['search_query: Has Congress done anything about its authority over tarrifs or taxes?']
query_embedding = model.encode(sentences)

In [ ]:
import numpy as np

# Correct the shape of query_embedding from (768, 1) to (1, 768)
# Assuming query_embedding is currently (768,)
query_embedding = np.array(query_embedding, dtype=np.float32).reshape(1, -1)

# Normalize the query embedding
normalized_query_embedding = query_embedding / np.linalg.norm(query_embedding)

# Perform the search
distances, indices = index.search(normalized_query_embedding, 5)

print("Distances:", distances)
print("Indices:", indices)

AssertionError: 

In [ ]:
distances

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [ ]:
indices

array([[  6136,  37882,  46375,  53832,  56127],
       [131938, 139097, 207202, 214361, 311798],
       [332546, 495362, 505346, 691970, 785666],
       ...,
       [ 74327, 110902, 186166, 267873, 270914],
       [ 18285,  20451,  27501,  29667,  58345],
       [ 46242,  53456,  94808,  96281, 109794]])

In [ ]:
indices[0][1]

np.int64(37882)

In [ ]:
import numpy as np

# Correct the shape of query_embedding from (768, 1) to (1, 768)
# The `query_embedding` variable in the kernel state is currently (768, 1).
# We reshape it back to (1, 768) for FAISS search.
query_embedding = np.array(query_embedding, dtype=np.float32).reshape(1, -1)

# Normalize the query embedding
normalized_query_embedding = query_embedding / np.linalg.norm(query_embedding)

# Perform the search
distances, indices = index.search(normalized_query_embedding, 5)

print("Distances:", distances)
print("Indices:", indices)

Distances: [[0.6206987  0.6565021  0.6565021  0.66295445 0.66295445]]
Indices: [[4805 8257 8303 4810 4815]]


In [ ]:
index.d

768

In [ ]:
normalized_query_embedding.shape

(1, 768)

In [5]:
import numpy as np
sentence = 'search_query: What is the Sports Agent Responsibility and Trust Act?'
query_embedding = np.array(model.encode(sentence), dtype=np.float32).reshape(1, -1)

In [6]:
normalized_query_embedding = query_embedding / np.linalg.norm(query_embedding)

# Perform the search
distances, indices = index.search(normalized_query_embedding, 5)

print("Distances:", distances)
print("Indices:", indices)

Distances: [[0.33569765 0.6110482  0.6117022  0.7032238  0.73457825]]
Indices: [[   3    1    4 1927    2]]


In [3]:
import numpy as np

In [5]:
query_embedding.shape

(1, 768)

In [6]:
import faiss

In [13]:
index = faiss.read_index("orders.index")

In [14]:
index.d

1

In [10]:
distances, indices = index.search(query_embedding, 5)

In [11]:
distances

array([[423.59012, 424.3512 , 424.3512 , 424.48834, 424.48834]],
      dtype=float32)

In [12]:
indices

array([[4805, 8257, 8303, 4810, 4815]])